version: "3"
services:
  web:
    build: ./web
    tty: true
    ports:
      - ${WEB_SERVER_PORT}:8080
    volumes:
      - ./web/app:/root/app
    depends_on:
      - server
  server:
    build: ./server
    tty: true
    ports:
      - ${DATABASE_SERVER_PORT}:8080
    volumes:
      - ./server/app:/go/github.com/sk409/todo
    depends_on:
      - database
  database:
    build: ./database
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
